version: 2

sources:
  - name: jaffle_shop
    description: This is a replica of stuff
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: One record per customer
        columns: 
          - name: id
            description: unique_id
            tests:
              - unique
              - not_null
          - name: first_name
            description: first name of customer
          - name: last_name
            description: last name of customer
      - name: orders
        description: One record per order.